### ISSUE TITLE
WikiLink Embedding - ![[..]]

### ISSUE THREAD

**Issue by srid** [srid/emanote#24]
Support for https://help.obsidian.md/How+to/Embed+files

- [x] Working prototype for .md and image files (#68)
- [x] Allow specifying note embed layout via Heist .tpl (#75)
- [x] ~~#88~~
- [x] #98 
- [ ] Other file types
  - [x] video
  - [x] audio
  - [x] pdf 
     - [x] #350
  - [x] Everything else? As code block. For eg., `foo.hs` gets syntax highlighted as haskell. https://github.com/srid/emanote/pull/719
    - [ ] Properties? ([file line nums](https://github.com/srid/neuron/issues/613), note snippet, ...)

**Comment by vcavallo** [comment]
I propose adding an item to the checklist above: 

- [ ] Allow embedding a specific subset _block_ of a file. 

For instance, the `## Some Section` H2 heading and all text until next section. Obsidian's syntax is basically: `![[filename#Some Section]]`

Obsidian supports this and it would be great to have parity between Obsidian editing and Emanote's rendered results.

**Comment by kukimik** [comment]
Embedding notes may create loops:

some_note.md:

```md
blah

![[other_note]]

blah
```

other_note.md:

```md
aaa

![[some_note]]

bbb
```

I've tried it with the live preview and couldn't open any of these notes in browser. Didn't have time to check memory/CPU usage etc., but perhaps the loops should be detected anyway?

**Comment by srid** [comment]
@vcavallo Yes, we need to address it in a fundamental manner first: https://github.com/EmaApps/emanote/discussions/105

@kukimik Could you open a new issue?

**Comment by srid** [comment]
I think we should also support source code embedding. For eg., `![[foo.hs]]` should include that as syntax highlighted code block. See also https://github.com/srid/neuron/issues/613 (not sure how that can be adopted for wiki links)

**Comment by kukimik** [comment]
> @kukimik Could you open a new issue?

With the current version of emanote I can display the page. It looks like this:

![Peek 2022-10-11 22-10](https://user-images.githubusercontent.com/53443372/195189389-2710e2e3-8ec3-4be7-a89c-2a2bf4eb4262.gif)

It no longer loops indefinitely. (Or maybe it never did? I upgraded my hardware in the meantime; maybe I was just lacking resources - which however would mean the resource consumption was excessive.)

So I can open an issue, but I don't treat the current behavior as a bug/problem.

**Comment by bolt12** [comment]
I am working on adding code files embedding support. I decided to hijack this post to ask if anyone knows a good way to solve this challenge I am facing:

The embed template itself. I realized I am not familiar with the way code blocks get rendered in HTML. I have inspected the source code and apparently they get transformed into `<code>` tags. The content of the code block then gets highlighted by using `<span>` of a specific class attribute so it gets properly highlighted (via `highlight.js`). The challenge then, is to take the code file content and embed it correctly in a `<code>` tag.

Does anyone more familiar or knowledgeable can see a way to do this?

Edit: I think I am on the right track. I figured I could just redundantly call `hljs.highlighAll();`.

**Comment by dpaetzel** [comment]
I know this issue has not seen activity in quite some time but I'd like to add another feature request: I'd like to be able to embed a file FILE without FILE's heading being generated. This would be very handy for having FILE contain a lot of `\newcommand{…}` definitions; I could then simply include it using `![[FILE|noheading]]` (or whatever syntax is used) whenever I want to write math without cluttering the output. Note that simply not setting a title within FILE does not work because HTML output then has FILE as title.

Note that doing `![[FILE]]` works in terms of math `\newcommand`'s being parsed in the importing file (but an empty block with a is generated). Example:

Test.md
```
# Test

![[FILE]]

$$
\XX
$$
```

FILE.md
```
$$
\newcommand{\XX}{\mathcal{X}}
$$
```

Output when opening Test in browser:

![image](https://github.com/srid/emanote/assets/974130/b052e458-2b1d-4922-87bd-3128f67401a1)

What I'd like to see:

![image](https://github.com/srid/emanote/assets/974130/70fe0102-a223-4cad-b954-7aa409904fcd)

**Comment by srid** [comment]
https://github.com/srid/emanote/pull/719 implements the last of this.

If anybody would like to request a new feature, please file a new issue.
